version: "3"

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www
    networks:
      - app-network

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    command: --innodb-use-native-aio=0
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
